# Generated by Django 5.0 on 2023-12-19 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='entry',
            new_name='entryModel',
        ),
    ]
